use std::fmt::Write;

use element::Location;
use language::Language;
use render::Emitter;
use style::{Keyframe, Media, Style};

pub type Highlight = fn(&str, Language) -> miette::Result<String>;

pub struct Serializer {
    pub html: String,
    root: String,
    highlight: Highlight,
}

impl Serializer {
    #[must_use]
    pub fn new(root: String, highlight: Highlight) -> Self {
        Self {
            html: String::new(),
            root,
            highlight,
        }
    }

    fn attributes(&mut self, name: &str, pairs: &[(String, String)]) {
        self.html.push('<');
        self.html.push_str(name);
        for (key, value) in pairs {
            write!(self.html, " {key}=\"").unwrap();
            escape::stream(&mut self.html, value);
            self.html.push('"');
        }
        self.html.push('>');
    }
}

impl Emitter for Serializer {
    fn open(&mut self, name: &str, attributes: &[(String, String)]) -> miette::Result<()> {
        self.attributes(name, attributes);
        Ok(())
    }

    fn close(&mut self, name: &str) -> miette::Result<()> {
        write!(self.html, "</{name}>").unwrap();
        Ok(())
    }

    fn void(&mut self, name: &str, attributes: &[(String, String)]) -> miette::Result<()> {
        self.attributes(name, attributes);
        Ok(())
    }

    fn text(&mut self, content: &str) -> miette::Result<()> {
        escape::stream(&mut self.html, content);
        Ok(())
    }

    fn raw(&mut self, content: &str) -> miette::Result<()> {
        self.html.push_str(content);
        Ok(())
    }

    fn code(
        &mut self,
        content: &str,
        language: Language,
        location: Option<&Location>,
    ) -> miette::Result<()> {
        let highlighted = (self.highlight)(content, language)?;
        write!(
            self.html,
            "<div class=\"{}\" {}=\"",
            code::block(),
            attribute::language().name()
        )
        .unwrap();
        escape::stream(&mut self.html, language.name());
        self.html.push_str("\">");
        if let Some(location) = location {
            write!(
                self.html,
                "<div class=\"{}\"><a class=\"{}\" href=\"",
                code::toolbar(),
                code::source()
            )
            .unwrap();
            self.html.push_str(&self.root);
            escape::stream(&mut self.html, &location.source);
            self.html.push_str("\">Source</a></div>");
        }
        self.html.push_str(&highlighted);
        self.html.push_str("</div>");
        Ok(())
    }

    fn indent(&mut self, depth: usize) -> miette::Result<()> {
        for _ in 0..depth * 2 {
            self.html.push(' ');
        }
        Ok(())
    }

    fn newline(&mut self) -> miette::Result<()> {
        self.html.push('\n');
        Ok(())
    }
}

pub fn page(page: &mut page::Page, highlight: Highlight) -> miette::Result<Serializer> {
    let headings = render::process(&mut page.body);
    render::outline(&mut page.body, &headings);

    let root = page.root.clone().unwrap_or_default();
    let mut serializer = Serializer::new(root, highlight);

    serializer
        .html
        .push_str("<!DOCTYPE html>\n<!-- Generated by Vantle::Web -->\n<html lang=\"en\"");
    data(
        &mut serializer.html,
        navigate::context().name(),
        page.context.as_deref(),
    );
    data(
        &mut serializer.html,
        navigate::page().name(),
        page.identifier.as_deref(),
    );
    data(
        &mut serializer.html,
        navigate::root().name(),
        page.root.as_deref(),
    );
    serializer.html.push_str(">\n");

    head(&mut serializer.html, page);
    serializer.html.push_str("<body>\n");

    render::render(&mut serializer, &page.body)?;

    serializer.html.push_str("</body>\n</html>\n");

    Ok(serializer)
}

fn data(html: &mut String, name: &str, value: Option<&str>) {
    if let Some(value) = value {
        html.push(' ');
        html.push_str(name);
        html.push_str("=\"");
        escape::stream(html, value);
        html.push('"');
    }
}

fn head(html: &mut String, page: &page::Page) {
    html.push_str("<head>\n");
    html.push_str("<meta charset=\"UTF-8\">\n");
    html.push_str("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
    html.push_str("<title>");
    escape::stream(html, &page.title);
    html.push_str("</title>\n");

    if let Some(ref path) = page.favicon {
        html.push_str("<link rel=\"icon\" type=\"image/x-icon\" href=\"");
        escape::stream(html, path);
        html.push_str("\">\n");
    }

    writeln!(
        html,
        "<script>try{{let d=document.documentElement;let t=localStorage.getItem('theme');\
         if(t)d.setAttribute('{}',t)}}catch(e){{}}</script>",
        theme::theme().name()
    )
    .unwrap();

    if let Some(ref path) = page.stylesheet {
        html.push_str("<link rel=\"stylesheet\" href=\"");
        escape::stream(html, path);
        html.push_str("\">\n");
    }

    if let Some(ref wasm) = page.wasm {
        html.push_str("<script type=\"module\">\nimport init from '");
        escape::stream(html, wasm);
        html.push_str("';\nawait init();\n</script>\n");
    }

    html.push_str("</head>\n");
}

#[must_use]
pub fn css(style: &Style) -> String {
    let mut output = String::from("/* Generated by Vantle::Web */\n\n");
    stylesheet(&mut output, style);
    output
}

pub fn stylesheet(output: &mut String, style: &Style) {
    indented(output, style, 0);
}

fn indented(output: &mut String, style: &Style, indent: usize) {
    let pad = "  ".repeat(indent);

    if !style.variables.is_empty() {
        writeln!(output, "{pad}:root {{").unwrap();
        properties(output, &style.variables, indent + 1);
        writeln!(output, "{pad}}}").unwrap();
    }

    for rule in &style.rules {
        output.push('\n');
        writeln!(output, "{pad}{} {{", rule.selector).unwrap();
        properties(output, &rule.properties.entries, indent + 1);
        writeln!(output, "{pad}}}").unwrap();
    }

    for keyframe in &style.keyframes {
        output.push('\n');
        animation(output, keyframe, indent);
    }

    for media in &style.media {
        output.push('\n');
        query(output, media, indent);
    }
}

fn properties(output: &mut String, entries: &[(String, String)], indent: usize) {
    let pad = "  ".repeat(indent);
    for (name, value) in entries {
        writeln!(output, "{pad}{name}: {value};").unwrap();
    }
}

fn animation(output: &mut String, keyframe: &Keyframe, indent: usize) {
    let pad = "  ".repeat(indent);
    writeln!(output, "{pad}@keyframes {} {{", keyframe.name).unwrap();
    for step in &keyframe.steps {
        writeln!(output, "{pad}  {} {{", step.selector).unwrap();
        properties(output, &step.properties.entries, indent + 2);
        writeln!(output, "{pad}  }}").unwrap();
    }
    writeln!(output, "{pad}}}").unwrap();
}

fn query(output: &mut String, media: &Media, indent: usize) {
    let pad = "  ".repeat(indent);
    writeln!(output, "{pad}@media ({}) {{", media.query).unwrap();
    indented(output, &media.style, indent + 1);
    writeln!(output, "{pad}}}").unwrap();
}
